/* ════════════════════════════════════════
   БАЗА ЦИТАТ
   ════════════════════════════════════════ */
const QUOTES = [
  { text: "Lay hold of today's task, and you will not need to depend so much upon tomorrow's.", author: "Seneca" },
  { text: "We don't abandon our pursuits because we despair of ever perfecting them.", author: "Epictetus" },
  { text: "Do everything as if it were the last thing you were doing in your life.", author: "Marcus Aurelius" },
  { text: "He who is begun has half done. Dare to be wise; begin.", author: "Horace" },
  { text: "Nothing is so fatiguing as the eternal hanging on of an uncompleted task.", author: "William James" },
  { text: "When you have to make a choice and don't make it, that in itself is a choice.", author: "William James" },
  { text: "Concentrate all your thoughts upon the work at hand.", author: "Alexander Graham Bell" },
  { text: "It is easier to resist at the beginning than at the end.", author: "Leonardo da Vinci" },
  { text: "Procrastination is the thief of time.", author: "Charles Dickens" },
  { text: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "You cannot escape the responsibility of tomorrow by evading it today.", author: "Abraham Lincoln" },
  { text: "The secret of getting started is breaking your complex overwhelming tasks into small manageable tasks.", author: "Mark Twain" },
  { text: "If we wait for the moment when everything is ready, we shall never begin.", author: "Ivan Turgenev" },
  { text: "It's a job that's never started that takes the longest to finish.", author: "J.R.R. Tolkien" },
  { text: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", author: "Stephen King" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
  { text: "Don't count on motivation. Count on discipline.", author: "Jocko Willink" },
  { text: "The professional does not wait for inspiration; he acts in anticipation of it.", author: "Steven Pressfield" },
  { text: "Resistance by definition is self-sabotage.", author: "Steven Pressfield" },
  { text: "Many people procrastinate because they're waiting for motivation to rise. Getting started is what leads motivation to rise.", author: "Adam Grant" },
  { text: "Procrastinating on something important is choosing to delay a better future.", author: "James Clear" },
  { text: "Do something instead of killing time. Because time is killing you.", author: "Paulo Coelho" },
  { text: "Begin while others are procrastinating. Work while others are wishing.", author: "William Arthur Ward" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Hurrying and delaying are alike ways of trying to resist the present.", author: "Alan Watts" },
  { text: "There is nothing so fatal to character as half finished tasks.", author: "David Lloyd George" },
  { text: "The price of inaction is far greater than the cost of making a mistake.", author: "Meister Eckhart" },
  { text: "You may not be punished for your procrastination, but you will be punished by it.", author: "Debasish Mridha" },
  { text: "Don't focus on the task and its complexity. Focus on the benefit you'll gain from it.", author: null },
];